export const APPLICANT_QUALIFICATION = {
    HIGH_SCHOOL_DIPLOMA: 'HIGH_SCHOOL_DIPLOMA',
    BACHELOR_DEGREE: 'BACHELOR_DEGREE',
    MASTER_DEGREE: 'MASTER_DEGREE',
    DOCTORAL_DEGREE: 'DOCTORAL_DEGREE'
};
